// Generated by tools/build_content.py from the mirror, then hand-edited.
// Live source: https://wforce.org/academic-partners

import type { PageContent } from "@/lib/content";

const page: PageContent = {
  route: "/academic-partners",
  title: "Academic Partners",
  eyebrow: "About",
  description: "WOS has partnered with institutions around the country to develop and deliver tailored certificate programs for our corporate partners. WOS has the unique",
  hero: null,
  images: [{"src": "/images/Alfa-college.jpg", "alt": ""}, {"src": "/images/App-Academy.svg", "alt": ""}, {"src": "/images/coding_dojo_blue.svg", "alt": ""}, {"src": "/images/Picture23.png", "alt": ""}, {"src": "/images/Picture24.png", "alt": ""}, {"src": "/images/CCV_logo.png", "alt": ""}, {"src": "/images/EC-Council-logo.webp", "alt": ""}, {"src": "/images/El-Paso-CC.jpg", "alt": ""}, {"src": "/images/fscj-logo-stacked-color.png", "alt": ""}, {"src": "/images/RGB-Red-Black_Small_GeneralAssembly-Stacked.png", "alt": ""}, {"src": "/images/Picture25.png", "alt": ""}, {"src": "/images/LSUGeauxPurp_sm2.png", "alt": ""}, {"src": "/images/Picture30.png", "alt": ""}, {"src": "/images/Picture29.png", "alt": ""}, {"src": "/images/Northeastern.png", "alt": ""}, {"src": "/images/Picture3.png", "alt": ""}, {"src": "/images/Picture28.png", "alt": ""}, {"src": "/images/Picture4.png", "alt": ""}, {"src": "/images/Picture31.png", "alt": ""}, {"src": "/images/Picture32.png", "alt": ""}, {"src": "/images/Picture33.png", "alt": ""}, {"src": "/images/192px-University_of_Akron_logo.svg.png", "alt": ""}, {"src": "/images/University-of-Groningen.png", "alt": ""}, {"src": "/images/UMDearborn_vertical.png", "alt": ""}, {"src": "/images/Picture38.png", "alt": ""}, {"src": "/images/Picture37.png", "alt": ""}, {"src": "/images/Picture6.png", "alt": ""}],
  lead: [{"kind": "para", "text": "WOS has partnered with institutions around the country to develop and deliver tailored certificate programs for our corporate partners. WOS has the unique ability to design programs based on specific company requirements. We create opportunities for comprehensive non-traditional learning that empowers our participants to learn the skills necessary to succeed in the workplace."}],
  sections: [],
};

export default page;
