// Generated by tools/build_content.py from the mirror, then hand-edited.
// Live source: https://wforce.org/become-a-partner

import type { PageContent } from "@/lib/content";

const page: PageContent = {
  route: "/become-a-partner",
  title: "Become A Partner",
  eyebrow: "Partners",
  description: "Need talent now?",
  hero: null,
  lead: [],
  sections: [{"heading": "Need talent now?", "blocks": [{"kind": "para", "text": "We source and vet talent from your local community with a background equipped for your needs. We strive to be as flexible as possible. We can create unique, customized services to meet your company’s specific financial and cultural needs. We have very few geographic barriers and can build and operate in most areas of the U.S. within a few short months. To learn more about our services and pricing, please contact us."}]}],
};

export default page;
