// Generated by tools/build_content.py from the mirror, then hand-edited.
// Live source: https://wforce.org/college-co-ops-and-internships

import type { PageContent } from "@/lib/content";

const page: PageContent = {
  route: "/college-co-ops-and-internships",
  title: "College Co-ops and Internships",
  eyebrow: "Managed Service Center",
  description: "WOS offers co-op and internship to college students at our myriad of offsite and onsite service programs. ​​This provides organizations with lower costs and",
  hero: {"src": "/images/internship.webp", "alt": ""},
  images: [],
  lead: [{"kind": "para", "text": "WOS offers co-op and internship to college students at our myriad of offsite and onsite service programs. ​​This provides organizations with lower costs and stronger talent pipelines that better prepare top students to transition into your company. We provide co-op students with complimentary professional development training and on-the job management that saves your staff time, recruitment and operational costs, as well as lower management oversight. The WOS professional development and management programs are specialized to support your specific culture and employee performance criteria. Once students complete the program they are better prepared to be integrated as full-time employees improving both performance and retention.​WOS manages the entire process, from defining the skills requirements, coordinating interviews, and working regularly with your staff to evaluate the performance of the interns. Co-op students, after completing an 8-12 month internship, can be converted to your employment at no additional charge, or they can become WOS employees and continue to service your account as WOS consultants.​​"}, {"kind": "para", "text": "How We Operate"}, {"kind": "heading", "text": "Recruit"}, {"kind": "heading", "text": "Develop"}, {"kind": "heading", "text": "Deliver"}, {"kind": "heading", "text": "Hire"}],
  sections: [],
};

export default page;
