// Generated by tools/build_content.py from the mirror, then hand-edited.
// Live source: https://wforce.org/consulting-to-hire-services
//
// The live page is an unfinished wireframe. Its opening line reads "Introduction to the
// COnsuling to Hire service goes her" and four body paragraphs are the literal strings
// "text…" and "more text…". That is almost certainly why it was built and never linked.
//
// The placeholders are dropped rather than carried, because this page is now in the
// header. Nothing here is written: every word below is text that is already on the live
// page. The page is thin and wants real copy from WOS.

import type { PageContent } from "@/lib/content";

const page: PageContent = {
  route: "/consulting-to-hire-services",
  title: "Consulting to Hire Services",
  eyebrow: "Services",
  // The live meta description is the truncated placeholder, so it would have shipped as
  // the search result. Replaced with the one real sentence the page already carries.
  description:
    "An agile, results-oriented approach that ensures you have the right people, in the right roles, at the right time.",
  hero: null,
  lead: [
    { kind: "para", text: "Consulting to Hire Services Offered by WOS" },
    {
      kind: "image",
      src: "/images/20160527_21_cropped-scaled-1-1.jpg",
      alt: "WOS consultants at work along a row of desktop workstations in a training lab.",
    },
    {
      kind: "image",
      src: "/images/shared-image_blur_crop.jpg",
      alt: "A WOS training session in progress, seen from outside the room through a glass wall.",
    },
    { kind: "heading", text: "Onsite & Remote Staffing" },
    {
      kind: "image",
      src: "/images/171206_4700_cropped-scaled-1-1.jpg",
      alt: "Three panellists seated at a WOS event, one speaking into a microphone.",
    },
    {
      kind: "para",
      text: "Discover the WOS difference: an agile, results-oriented approach that ensures you have the right people, in the right roles, at the right time. Let us help you build a workforce that drives growth and innovation.",
    },
  ],
  sections: [],
};

export default page;
