// Generated by tools/build_content.py from the mirror, then hand-edited.
// Live source: https://wforce.org/consulting-to-hire-services
//
// The live page is an unfinished wireframe. Its opening line reads "Introduction to the
// COnsuling to Hire service goes her" and four body paragraphs are the literal strings
// "text…" and "more text…". That is almost certainly why it was built and never linked.
//
// The placeholders are dropped rather than carried, because this page is now in the
// header. Nothing here is written: every word below is text that is already on the live
// page.
//
// What the page had left was 46 words and three stock photographs stacked full-width,
// and because it has no h2 the extractor put all of it in the lead, so it rendered
// inside the dark header. The photographs now carry the three sibling pages as a hub
// grid in app/consulting-to-hire-services/page.tsx, which is what an Overview in a
// four-item nav group is for. The page still wants real copy from WOS.

import type { PageContent } from "@/lib/content";

const page: PageContent = {
  route: "/consulting-to-hire-services",
  title: "Consulting to Hire Services",
  eyebrow: "Services",
  // The live meta description is the truncated placeholder, so it would have shipped as
  // the search result. Replaced with the one real sentence the page already carries.
  description:
    "An agile, results-oriented approach that ensures you have the right people, in the right roles, at the right time.",
  hero: null,
  lead: [
    {
      kind: "para",
      text: "Discover the WOS difference: an agile, results-oriented approach that ensures you have the right people, in the right roles, at the right time. Let us help you build a workforce that drives growth and innovation.",
    },
  ],
  sections: [],
};

export default page;
