// Generated by tools/build_content.py from the mirror, then hand-edited.
// Live source: https://wforce.org/consulting-to-hire-services

import type { PageContent } from "@/lib/content";

const page: PageContent = {
  route: "/consulting-to-hire-services",
  title: "Consulting to Hire Services",
  eyebrow: "Consulting to Hire Services",
  description: "Introduction to the COnsuling to Hire service goes her",
  hero: null,
  lead: [{"kind": "para", "text": "Introduction to the COnsuling to Hire service goes her"}, {"kind": "para", "text": "Consulting to Hire Services Offered by WOS"}, {"kind": "image", "src": "/images/20160527_21_cropped-scaled-1-1.jpg", "alt": ""}, {"kind": "para", "text": "text…"}, {"kind": "image", "src": "/images/shared-image_blur_crop.jpg", "alt": ""}, {"kind": "heading", "text": "Onsite & Remote Staffing"}, {"kind": "para", "text": "text…"}, {"kind": "image", "src": "/images/171206_4700_cropped-scaled-1-1.jpg", "alt": ""}, {"kind": "para", "text": "text…"}, {"kind": "para", "text": "more text…"}, {"kind": "para", "text": "Discover the WOS difference: an agile, results-oriented approach that ensures you have the right people, in the right roles, at the right time. Let us help you build a workforce that drives growth and innovation."}],
  sections: [],
};

export default page;
