// Generated by tools/build_content.py from the mirror, then hand-edited.
// Live source: https://wforce.org/corporate-partners

import type { PageContent } from "@/lib/content";

const page: PageContent = {
  route: "/corporate-partners",
  title: "Corporate Partners",
  eyebrow: "About",
  description: "WOS partners with corporations to provide early-career talent from veterans and underserved local communities. Since our inception, we have partnered with",
  lead: [{"kind": "para", "text": "WOS partners with corporations to provide early-career talent from veterans and underserved local communities. Since our inception, we have partnered with over 65 corporations, big and small, in the U.S. and worldwide that represent a wide range of industries with unique talent needs."}],
  sections: [{"heading": "Corporate Partners Served", "blocks": []}],
};

export default page;
