// Generated by tools/build_content.py from the mirror, then hand-edited.
// Live source: https://wforce.org/cyber-security

import type { PageContent } from "@/lib/content";

const page: PageContent = {
  route: "/cyber-security",
  title: "Cyber Security Monitoring (SOC)",
  eyebrow: "Managed Service Center",
  description: "WOS provides continuous monitoring that reduces noise and speeds response. We provide L1 and L2 analysts, operate your SIEM and EDR stack, and coordinate with",
  lead: [{"kind": "para", "text": "WOS provides continuous monitoring that reduces noise and speeds response. We provide L1 and L2 analysts, operate your SIEM and EDR stack, and coordinate with your internal or third party incident responders."}, {"kind": "para", "text": "Scope:"}, {"kind": "heading", "text": "Around the clock alert monitoring and triage"}, {"kind": "heading", "text": "SIEM rule tuning and use case development"}, {"kind": "heading", "text": "EDR monitoring, isolation requests, and containment support"}, {"kind": "heading", "text": "Vulnerability scan scheduling and exception tracking"}, {"kind": "heading", "text": "Threat intel enrichment and basic hunting"}, {"kind": "heading", "text": "Incident communications and post-incident reviews"}, {"kind": "para", "text": "Playbooks We Operate :"}, {"kind": "heading", "text": "Phishing"}, {"kind": "heading", "text": "Credential Stuffing"}, {"kind": "heading", "text": "Suspicious Authentication"}, {"kind": "heading", "text": "Malware Detection"}, {"kind": "heading", "text": "Lateral Movement"}, {"kind": "heading", "text": "Data Exfiltration Indicators"}, {"kind": "heading", "text": "Ransomware Precursors"}, {"kind": "heading", "text": "Insider Anomalies"}, {"kind": "para", "text": "Our Stack"}, {"kind": "list", "items": ["Microsoft Sentinel", "Splunk", "Chronicle", "CrowdStrike", "Microsoft Defender", "SentinelOne", "Rapid7", "Tenable", "Qualys", "Okta", "Zscaler"]}, {"kind": "para", "text": "Governance :"}, {"kind": "para", "text": "Clear RACI with your security lead, monthly tabletop or simulation, and a use case roadmap that aligns to your risk register."}, {"kind": "para", "text": "What we are not :"}, {"kind": "para", "text": "We are not a legal incident response counsel or forensic lead. When those are needed, we integrate with your chosen providers and drive coordination."}, {"kind": "para", "text": "Begin with a readiness assessment that targets your top alert types."}],
  sections: [],
};

export default page;
