// Generated by tools/build_content.py from the mirror, then hand-edited.
// Live source: https://wforce.org/data-analytics-and-ai

import type { PageContent } from "@/lib/content";

const page: PageContent = {
  route: "/data-analytics-and-ai",
  title: "Data Analytics and AI",
  eyebrow: "Managed Service Center",
  description: "WOS works to hire, train and manage resources to implement the requirements of Data and AI-enabled technologies and the needed workflows to make advanced",
  hero: {"src": "/images/data-ai.webp", "alt": ""},
  lead: [{"kind": "para", "text": "WOS works to hire, train and manage resources to implement the requirements of Data and AI-enabled technologies and the needed workflows to make advanced technologies work. We offer expert technical, scientific and process automation support, data analysis, plan and implement effective AI solutions​."}],
  sections: [{"heading": "Our Services", "blocks": [{"kind": "list", "items": ["Well-designed, cost-effective AI workflows, and ROI analysis​", "Design, planning and implementation support​", "Security, compliance and data privacy​", "Efficient Data Management​", "Quality Assurance and Performance Monitoring ​", "Training and Documentation​", "Training and Documentation​"]}]}, {"heading": "WOS Advantage", "blocks": [{"kind": "list", "items": ["Skilled Resources​", "Flexible and sustainable workforce​", "Fully outsourced, hybrid or onsite​", "Trained and optionally managed by WOS experts​"]}, {"kind": "para", "text": "Book a consultation today and see how you can leverage your Data and AI to empower your business."}], "density": "feature", "fill": "dark"}],
};

export default page;
