// Generated by tools/build_content.py from the mirror, then hand-edited.
// Live source: https://wforce.org/data-analytics-and-ai

import type { PageContent } from "@/lib/content";

const page: PageContent = {
  route: "/data-analytics-and-ai",
  title: "Data Analytics and AI",
  eyebrow: "Managed Service Center",
  description: "WOS works to hire, train and manage resources to implement the requirements of Data and AI-enabled technologies and the needed workflows to make advanced",
  hero: {"src": "/images/data-ai.webp", "alt": ""},
  images: [],
  lead: [{"kind": "para", "text": "WOS works to hire, train and manage resources to implement the requirements of Data and AI-enabled technologies and the needed workflows to make advanced technologies work. We offer expert technical, scientific and process automation support, data analysis, plan and implement effective AI solutions​."}, {"kind": "para", "text": "Our Services:"}, {"kind": "heading", "text": "Well-designed, cost-effective AI workflows, and ROI analysis​"}, {"kind": "heading", "text": "Design, planning and implementation support​"}, {"kind": "heading", "text": "Security, compliance and data privacy​"}, {"kind": "heading", "text": "Efficient Data Management​"}, {"kind": "heading", "text": "Quality Assurance and Performance Monitoring ​"}, {"kind": "heading", "text": "Training and Documentation​"}, {"kind": "heading", "text": "Training and Documentation​"}, {"kind": "para", "text": "WOS Advantage:"}, {"kind": "heading", "text": "Skilled Resources​"}, {"kind": "heading", "text": "Flexible and sustainable workforce​"}, {"kind": "heading", "text": "Fully outsourced, hybrid or onsite​"}, {"kind": "heading", "text": "Trained and optionally managed by WOS experts​"}, {"kind": "para", "text": "Book a consultation today and see how you can leverage your Data and AI to empower your business."}],
  sections: [],
};

export default page;
