// Generated by tools/build_content.py from the mirror, then hand-edited.
// Live source: https://wforce.org/faqs

import type { PageContent } from "@/lib/content";

const page: PageContent = {
  route: "/faqs",
  title: "FAQs",
  eyebrow: "About",
  description: "You can apply online. See a list of our open jobs.",
  hero: null,
  images: [],
  lead: [{"kind": "heading", "text": "How do I apply?"}, {"kind": "para", "text": "You can apply online. See a list of our open jobs."}, {"kind": "heading", "text": "How often do programs become available?"}, {"kind": "para", "text": "There are no set dates for our career opportunities. We work with our partner corporations to assess their employment needs and recruit accordingly. We always add new positions to our website as they become available."}, {"kind": "heading", "text": "When will I be notified if I’m accepted?"}, {"kind": "para", "text": "Upon completion of the selection process, successful candidates will be notified by a member of our team."}, {"kind": "heading", "text": "Can I re-apply if I don’t get accepted?"}, {"kind": "para", "text": "Yes. We encourage you to re-apply if you are not accepted the first time."}, {"kind": "heading", "text": "Do I have to sign a contract?"}, {"kind": "para", "text": "No, there are no contracts. All we ask is that you show up on time, complete your tasks by assigned deadlines, and dedicate yourself to succeeding in your new position."}, {"kind": "heading", "text": "How does the admissions process work?"}, {"kind": "para", "text": "Once you submit an application, you will be contacted by WOS. If we believe you may be a good fit, we will begin our selection process which can include phone interviews, in-person interviews and/or program selection events. Program selection events are for our Cohort programs only. Typically this takes place over 2-4 sessions during one week where you will complete assessments and/or give presentations that may be in the presence of the hiring corporation."}],
  sections: [],
};

export default page;
