// Generated by tools/build_content.py from the mirror, then hand-edited.
// Live source: https://wforce.org/financials

import type { PageContent } from "@/lib/content";

const page: PageContent = {
  route: "/financials",
  title: "Financials",
  eyebrow: "About",
  description: "Form - 990.",
  hero: null,
  lead: [],
  sections: [{"heading": "Form – 990 .", "blocks": [{"kind": "list", "items": ["Year Ending September 30th, 2025", "Year Ending September 30th, 2024", "Year Ending September 30th, 2023", "Year Ending September 30th, 2022", "Year Ending September 30th, 2021"]}]}, {"heading": "Audited Financial Statements", "blocks": [{"kind": "list", "items": ["Year Ending September 30th, 2025", "Year Ending September 30th, 2024", "Year Ending September 30th, 2023", "Year Ending September 30th, 2022", "Year Ending September 30th, 2021"]}]}],
};

export default page;
