// Generated by tools/build_content.py from the mirror, then hand-edited.
// Live source: https://wforce.org/itsupport

import type { PageContent } from "@/lib/content";

const page: PageContent = {
  route: "/itsupport",
  title: "Customer Service and IT Support Desk",
  eyebrow: "Managed Service Center",
  description: "WOS offers a right-sized service desk that handles customer care and end user IT support across phone, email, chat, and self-service. We can start up new",
  hero: {"src": "/images/customer-service.webp", "alt": ""},
  lead: [{"kind": "para", "text": "WOS offers a right-sized service desk that handles customer care and end user IT support across phone, email, chat, and self-service. We can start up new desks or augment your existing operation."}, {"kind": "para", "text": "From Account unlocks, MFA, VPN, device support, Office 365, basic networking, Ticket intake and triage, knowledge base creation, self-service portal maintenance to Incident, request, and problem management using your ITSM platform and Workforce management, QA monitoring, coaching, and reporting"}],
  sections: [{"blocks": [{"kind": "cards", "items": [{"title": "Self Service & Knowledge", "body": "Curate FAQs, guided flows, and simple automations that deflect common requests."}, {"title": "First line Support", "body": "Verify identity, triage, and resolve the most frequent issues with clear scripts and runbooks."}, {"title": "Advanced Technical Support", "body": "Deeper troubleshooting for accounts, devices, networking, and core applications."}, {"title": "Local Desk Side support", "body": "On site help for hardware, peripherals, conference rooms, and moves, adds, changes."}]}]}, {"heading": "Delivery Options", "blocks": [{"kind": "list", "items": ["Onsite, Remote or Hybrid", "Onshore US, nearshore Costa Rica or Blended", "Dedicated or Shared Agents", "English and Spanish Coverage"]}], "fill": "tint"}, {"heading": "Tools We Work with", "blocks": [{"kind": "list", "items": ["ServiceNow", "Jira Service Management", "Freshservice", "Zendesk", "Five9", "NICE", "Genesys Cloud", "Microsoft 365", "Google Workspace", "Okta", "Duo"]}]}, {"heading": "How we Launch", "blocks": [{"kind": "steps", "items": [{"title": "Discovery and call type Mapping"}, {"title": "Knowledge capture and runbook drafting"}, {"title": "Pilot with shadow support and UAT"}, {"title": "Gradual volume ramp with daily reporting"}, {"title": "Monthly tune-ups on staffing, scripts, and KB articles"}]}], "density": "feature", "fill": "dark"}, {"heading": "Proof you can see", "blocks": [{"kind": "para", "text": "Weekly operations packs, call and ticket QA samples with coaching notes, and a quarterly improvement plan focused on deflection and first contact resolution."}], "fill": "tint"}, {"blocks": [{"kind": "cta", "text": "Start with a pilot focused on your top five contact drivers.", "href": "/contact", "label": "Schedule a free consultation"}], "fill": "dark", "density": "feature"}],
};

export default page;
