// Generated by tools/build_content.py from the mirror, then hand-edited.
// Live source: https://wforce.org/legacy-application-support

import type { PageContent } from "@/lib/content";

const page: PageContent = {
  route: "/legacy-application-support",
  title: "Legacy Application Support",
  eyebrow: "Managed Service Center",
  description: "Sustain and evolve the systems you rely on while you plan the next step. We stabilize, support, and modernize legacy apps so your teams can focus on roadmaps.",
  hero: {"src": "/images/customized-solutions.png", "alt": ""},
  lead: [{"kind": "para", "text": "Sustain and evolve the systems you rely on while you plan the next step. We stabilize, support, and modernize legacy apps so your teams can focus on roadmaps."}, {"kind": "para", "text": "Common Stacks"}, {"kind": "list", "items": [".NET and Java apps", "SQL Server and Oracle PL/SQL", "Classic SharePoint", "Access", "VBA automations", "Older Web Frameworks", "Reporting Platforms", "Batch Jobs", "COBOL"]}, {"kind": "para", "text": "Services"}, {"kind": "heading", "text": "L2 and L3 support with defined defect queues"}, {"kind": "heading", "text": "Bug fixes, minor enhancements, and release packaging"}, {"kind": "heading", "text": "Test automation for regression safety"}, {"kind": "heading", "text": "Performance tuning and database maintenance"}, {"kind": "heading", "text": "Documentation, code hygiene, and knowledge transfer"}, {"kind": "heading", "text": "Modernization roadmap and cost model"}, {"kind": "para", "text": "Three Phase Approach"}, {"kind": "heading", "text": "1. STABILIZE"}, {"kind": "heading", "text": "Backlog Triage, Hotfixes, Monitoring, and Runbooks"}, {"kind": "heading", "text": "2. Sustain"}, {"kind": "heading", "text": "Defined cadence of sprint work"}, {"kind": "heading", "text": "3. Modernize"}, {"kind": "heading", "text": "Target state design, Component replacement, and Cloud migration plans"}, {"kind": "para", "text": "Start with a six week stabilization program that produces your runbook and modernization options."}],
  sections: [],
};

export default page;
