// Generated by tools/build_content.py from the mirror, then hand-edited.
// Live source: https://wforce.org/legacy-application-support

import type { PageContent } from "@/lib/content";

const page: PageContent = {
  route: "/legacy-application-support",
  title: "Legacy Application Support",
  eyebrow: "Managed Service Center",
  description: "Sustain and evolve the systems you rely on while you plan the next step. We stabilize, support, and modernize legacy apps so your teams can focus on roadmaps.",
  hero: {"src": "/images/customized-solutions.png", "alt": ""},
  lead: [{"kind": "para", "text": "Sustain and evolve the systems you rely on while you plan the next step. We stabilize, support, and modernize legacy apps so your teams can focus on roadmaps."}],
  sections: [{"heading": "Common Stacks", "blocks": [{"kind": "list", "items": [".NET and Java apps", "SQL Server and Oracle PL/SQL", "Classic SharePoint", "Access", "VBA automations", "Older Web Frameworks", "Reporting Platforms", "Batch Jobs", "COBOL"]}, {"kind": "list", "items": ["Services", "L2 and L3 support with defined defect queues", "Bug fixes, minor enhancements, and release packaging", "Test automation for regression safety", "Performance tuning and database maintenance", "Documentation, code hygiene, and knowledge transfer", "Modernization roadmap and cost model", "Three Phase Approach", "1. STABILIZE", "Backlog Triage, Hotfixes, Monitoring, and Runbooks", "2. Sustain", "Defined cadence of sprint work", "3. Modernize", "Target state design, Component replacement, and Cloud migration plans"]}, {"kind": "para", "text": "Start with a six week stabilization program that produces your runbook and modernization options."}]}],
};

export default page;
