// Generated by tools/build_content.py from the mirror, then hand-edited.
// Live source: https://wforce.org/locations
//
// The addresses moved to content/offices.ts, which holds them as records rather than as
// one line of prose each, and app/locations/page.tsx renders them beside their maps.
// This file keeps the page's title and chrome only. Leaving the old prose sections here
// would mean two copies of every address with nothing keeping them in sync.

import type { PageContent } from "@/lib/content";

const page: PageContent = {
  route: "/locations",
  title: "Locations",
  eyebrow: "About",
  description: "WOS Headquarters",
  hero: null,
  lead: [],
  sections: [],
};

export default page;
