// Generated by tools/build_content.py from the mirror, then hand-edited.
// Live source: https://wforce.org/managed-service-centers

import type { PageContent } from "@/lib/content";

const page: PageContent = {
  route: "/managed-service-centers",
  title: "Managed Service Centers",
  eyebrow: "Consulting to Hire Services",
  description: "Our Managed Service Center provides a comprehensive solution designed to optimize your business and drive growth. Our practical managed services blend trained",
  hero: null,
  lead: [{"kind": "para", "text": "Our Managed Service Center provides a comprehensive solution designed to optimize your business and drive growth. Our practical managed services blend trained talent, clear deliverables, and a flexible delivery model across the United States and Costa Rica. We build teams around your goals, train them for your environment, and manage outcomes you can see."}],
  sections: [{"heading": "How We Deliver", "blocks": [{"kind": "cards", "items": [{"title": "Talent & training", "body": "We recruit for aptitude and attitude, then train for your stack and workflows. Every new team member completes role based training and passes scenario based assessments before going live."}, {"title": "Location & coverage", "body": "Teams across the U.S. and Costa Rica provide coverage across time zones. Spanish and English support is available. We can ramp to full day coverage where needed."}, {"title": "Governance", "body": "You get a named Operations Manager, daily huddles during launch, weekly service reviews, and a monthly business review with actions. Risk, compliance, and security are part of the agenda."}, {"title": "Security & Compliance", "body": "Background checks where required, least privilege access, MFA, secure device standards, encrypted data at rest and in transit, and documented change control. We align to common control frameworks and respect your internal policies."}]}], "fill": "dark", "density": "feature"}],
};

export default page;
