// Generated by tools/build_content.py from the mirror, then hand-edited.
// Live source: https://wforce.org/on-site-remote-staffing
//
// The live page has no h2 at all, so the extractor put the whole body in the lead and
// ContentPage rendered it inside the dark header, where the five step headings came out
// slate on slate. Re-sectioned here by hand: the four numbered stages are a `steps`
// block, which is what they always were.
//
// "Our Expertise" was a two-word paragraph above the intro. It is the live meta
// description verbatim, so it survives as `description` rather than as a body paragraph
// that looked like a heading without being one. No other word is changed.

import type { PageContent } from "@/lib/content";

const page: PageContent = {
  route: "/on-site-remote-staffing",
  title: "On-Site & Remote Staffing",
  eyebrow: "Consulting to Hire Services",
  description: "Our Expertise",
  hero: { src: "/images/educational-service.webp", alt: "" },
  lead: [
    {
      kind: "para",
      text: "At WOS, we go beyond traditional hiring and placement programs by offering a risk-free, flexible staffing solution tailored to your business needs. We specialize in recruiting and training talent from local communities, placing them in your organization as WOS-employed consultants who are prepared to deliver immediate value.",
    },
  ],
  sections: [
    // The live intro is one ~180-word paragraph. Split at sentence boundaries so the
    // header carries an opening rather than the whole thing, and the remainder keeps
    // its original position above the model. No heading invented for it: the live page
    // gives it none, and writing one here would be copy rather than structure.
    {
      blocks: [
        {
          kind: "para",
          text: "Throughout this entire process we provide both your corporation and our consultants with a dedicated Client Service Manager. Our Client Service Managers work with you to ensure expectations are being met and provide our consultants with the mentorship and support they need to succeed at your corporation.",
        },
        {
          kind: "para",
          text: "Hiring managers can experience our consultants on-site and eventually hire them full-time based on availability and need. This flexibility allows you to meet hiring directives while establishing effective strategies that promote workplace assimilation. As in all WOS staffing solutions, we do not assess a premium nor a penalty if you choose to transition WOS staff to a full-time employee. We offer a range of services and always customize our talent solutions to ensure you get the talent you need in the ways you need it.",
        },
      ],
    },
    {
      heading: "Staff Augmentation Model",
      fill: "dark",
      density: "feature",
      blocks: [
        {
          kind: "para",
          text: "WOS directs all aspects of the program, working with you to assure a timely, efficient, and successful transition of our participants into the workplace.",
        },
        {
          kind: "steps",
          items: [
            {
              title: "Determine Need",
              body: "WOS listens to you about your wants and needs. We work together to create a plan to guide trainees into open positions. Once we agree on a plan, we agree upon the timeframe for deliverables.",
            },
            {
              title: "Talent Acquisition",
              body: "Our recruiters identify promising talent among local communities. WOS candidates are selected to train in their industrial or commercial field choice. WOS candidates have the passion, drive, and dedication to be solid long-lasting additions to your team.",
            },
            {
              title: "Training & Certification",
              body: "Recruits develop purpose, responsibility, and aptitude in an industrial field. Training is hands-on and personally guided by WOS mentors. Recruits who complete our training and mentorship programs are invited to become your future satellite employees.",
            },
            {
              title: "WOS Employment",
              body: "Program participants begin full-time work at Corporate Sponsor as WOS employees after initial training. Program participants are eligible to be hired away by Corporate Sponsor at no additional cost after completion of full-time work. Corporate Sponsor has the ability to extend a WOS Program participants beyond the full-time consultancy period.",
            },
          ],
        },
      ],
    }

  ],
};

export default page;
