// Generated by tools/build_content.py from the mirror, then hand-edited.
// Live source: https://wforce.org/professional-development

import type { PageContent } from "@/lib/content";

const page: PageContent = {
  route: "/professional-development",
  title: "Professional Development",
  eyebrow: "Educational Services",
  description: "Aligned with the values of WOS and our clients, this program empowers employees to develop self-esteem, confidence, lifelong learning, and metacognition. It",
  lead: [{"kind": "para", "text": "Aligned with the values of WOS and our clients, this program empowers employees to develop self-esteem, confidence, lifelong learning, and metacognition. It also instills personal and professional core values and business culture literacy for workplace success. Our comprehensive mentorship through the interpersonal skills training cultivates professionals who are less prone to engage in workplace conflict, turnover, or absenteeism. Professional Development acts as a catalyst for equipping employees from underserved communities and veterans with the necessary interpersonal skills to successfully navigate the workplace."}, {"kind": "para", "text": "Our interpersonal skills training is tailored for motivated professionals seeking to enrich both their professional and personal lives. With four courses aligned to the Langer Workforce Maturity Arc, our program ensures individuals are prepared for lasting success in the workplace by enhancing their readiness to assimilate effectively into professional environments. The Langer Workforce Maturity Arc , rooted in Columbia University research, has been fundamental to WOS’ nearly two decades of operation."}],
  sections: [{"heading": "Courses", "blocks": [{"kind": "heading", "text": "Self-Esteem"}, {"kind": "para", "text": "Provides a framework for further developing one’s self-awareness through an examination of self-esteem and self-acceptance, values, and career and life visioning."}, {"kind": "heading", "text": "Metacognition"}, {"kind": "para", "text": "Identifies knowledge, skills, and attitudes needed to support individual and organization learning."}, {"kind": "heading", "text": "Socio-Economic Values"}, {"kind": "para", "text": "Covers navigation strategies for integrating personal, community, and professional values and goals through the application of various approaches."}, {"kind": "heading", "text": "Business Culture"}, {"kind": "para", "text": "Lays the groundwork for exploring professionalism, employer and employee expectations, conflict management, teamwork, and other interpersonal skills of leadership, ethical behavior, citizenship, and civic literacy."}, {"kind": "para", "text": "With 40 hours of immersive in-person, virtual, or self-paced instruction, Professional Development is a deep dive into the interpersonal skills needed to be successful at work, school, or in your employees’ personal lives."}]}],
};

export default page;
