// Generated by tools/build_content.py from the mirror, then hand-edited.
// Live source: https://wforce.org/shared-services

import type { PageContent } from "@/lib/content";

const page: PageContent = {
  route: "/shared-services",
  title: "Shared Services",
  eyebrow: "Managed Service Center",
  description: "WOS provides process support that clears the busywork without sacrificing accuracy. We handle repeatable tasks so your team can focus on higher value work.",
  hero: {"src": "/images/scalable-services.png", "alt": ""},
  lead: [{"kind": "para", "text": "WOS provides process support that clears the busywork without sacrificing accuracy. We handle repeatable tasks so your team can focus on higher value work."}],
  sections: [{"blocks": [{"kind": "cards", "items": [{"title": "HR Operations", "body": "Onboarding Packets, I9 and Document Checks, Background Check Coordination, Benefits Data Entry"}, {"title": "Finance Operations", "body": "AP, AR, Billing Prep, Expense Audits, PO Matching"}, {"title": "Sales operations", "body": "CRM Hygiene, List Building, Enrichment, Quoting Support"}]}, {"kind": "list", "items": ["Recruiting operations", "Resume Screening, Interview Scheduling, Candidate Communications", "Data operations", "Data Entry, Cleansing, Deduping, Report Building", "Content operations"]}, {"kind": "para", "text": "Catalog Updates, Listings Moderation, Knowledge Base Maintenance"}]}, {"heading": "Quality and Controls", "blocks": [{"kind": "para", "text": "Work instructions and SOPs for every task, dual control for sensitive changes, sample based QA with acceptance thresholds, audit logs, and regular control reviews."}, {"kind": "para", "text": "We measure accuracy, speed, and cost to set the long term model."}], "density": "feature", "fill": "dark"}],
};

export default page;
