// Generated by tools/build_content.py from the mirror, then hand-edited.
// Live source: https://wforce.org/staff-augmentation

import type { PageContent } from "@/lib/content";

const page: PageContent = {
  route: "/staff-augmentation",
  title: "Staff Augmentation",
  eyebrow: "Consulting to Hire Services",
  description: "Our Expertise",
  hero: {"src": "/images/educational-service.webp", "alt": ""},
  lead: [{"kind": "para", "text": "Our Expertise"}, {"kind": "para", "text": "At WOS, we go beyond traditional hiring and placement programs by offering a risk-free, flexible staffing solution tailored to your business needs. We specialize in recruiting and training talent from local communities, placing them in your organization as WOS-employed consultants who are prepared to deliver immediate value. Throughout this entire process we provide both your corporation and our consultants with a dedicated Client Service Manager. Our Client Service Managers work with you to ensure expectations are being met and provide our consultants with the mentorship and support they need to succeed at your corporation. Hiring managers can experience our consultants on-site and eventually hire them full-time based on availability and need. This flexibility allows you to meet hiring directives while establishing effective strategies that promote workplace assimilation. As in all WOS staffing solutions, we do not assess a premium nor a penalty if you choose to transition WOS staff to a full-time employee. We offer a range of services and always customize our talent solutions to ensure you get the talent you need in the ways you need it."}],
  sections: [{"blocks": [{"kind": "cards", "items": [{"title": "Staff Augmentation Model", "body": "WOS directs all aspects of the program, working with you to assure a timely, efficient, and successful transition of our participants into the workplace."}, {"title": "1. Determine Need", "body": "WOS listens to you about your wants and needs. We work together to create a plan to guide trainees into open positions. Once we agree on a plan, we agree upon the timeframe for deliverables."}, {"title": "2. Talent Acquisition", "body": "Our recruiters identify promising talent among local communities. WOS candidates are selected to train in their industrial or commercial field choice. WOS candidates have the passion, drive, and dedication to be solid long-lasting additions to your team."}, {"title": "3. Training & Certification", "body": "Recruits develop purpose, responsibility, and aptitude in an industrial field. Training is hands-on and personally guided by WOS mentors. Recruits who complete our training and mentorship programs are invited to become your future satellite employees."}, {"title": "4. WOS Employment", "body": "Program participants begin full-time work at Corporate Sponsor as WOS employees after initial training. Program participants are eligible to be hired away by Corporate Sponsor at no additional cost after completion of full-time work. Corporate Sponsor has the ability to extend a WOS Program participants beyond the full-time consultancy period."}]}]}],
};

export default page;
