#!/usr/bin/env python3
"""
Turn the extracted JSON into typed content/*.ts files.

Sections break at each h2, which is how the live pages are structured. Everything above
the first h2 becomes the lead. Runs of <li> collapse into one list.

Titles and descriptions come from the live <title> and meta description so search
results do not change in the migration.

Usage: python3 tools/build_content.py
"""

import html
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
MIRROR = os.path.join(HERE, "..", "..", "wforce-mirror", "wforce.org")
EXTRACTED = os.path.join(HERE, "extracted")
DEST = os.path.join(HERE, "..", "content")

# Which part of the site each page belongs to. Drives the hero eyebrow, so it says
# where the reader is rather than repeating the page title.
EYEBROW = {
    "our-story": "About", "team": "About", "board-of-directors": "About",
    "academic-advisory-board": "About", "corporate-partners": "About",
    "academic-partners": "About", "locations": "About", "financials": "About",
    "faqs": "About", "managed-service-centers": "Consulting to Hire Services",
    "facilities-management": "Consulting to Hire Services",
    "on-site-remote-staffing": "Consulting to Hire Services",
    "educational-services": "Educational Services",
    "professional-development-fundamentals": "Educational Services",
    "professional-development": "Educational Services",
    "advisory-services": "Advisory Services", "ai-services": "Advisory Services",
    "langer-arc": "Research", "itsupport": "Managed Service Center",
    "cyber-security": "Managed Service Center",
    "legacy-application-support": "Managed Service Center",
    "data-analytics-and-ai": "Managed Service Center",
    "shared-services": "Managed Service Center",
    "college-co-ops-and-internships": "Managed Service Center",
    "cohorts": "Programs", "become-a-partner": "Partners", "blog": "News & Events",
    "contact": "Contact", "donate": "Support WOS", "privacy-policy": "Legal",
}

# Built by hand from the extracted output. These pages have a card grid, a person
# grid, a form, or a document list, none of which survive a prose renderer.
BESPOKE = {"", "team", "board-of-directors", "academic-advisory-board", "blog"}

SUFFIX = re.compile(r"\s*[-|]\s*Workforce Opportunity Services\s*$", re.I)


def meta(route):
    src = open(os.path.join(MIRROR, route, "index.html"), encoding="utf-8",
               errors="replace").read()
    title = re.search(r"<title[^>]*>(.*?)</title>", src, re.S | re.I)
    desc = re.search(r'<meta\s+name="description"\s+content="([^"]*)"', src, re.I)
    title = SUFFIX.sub("", html.unescape(title.group(1)).strip()) if title else route
    return title, html.unescape(desc.group(1)).strip() if desc else ""


def ts(value):
    return json.dumps(value, ensure_ascii=False)


def shape(blocks):
    lead, sections, current = [], [], None
    for b in blocks:
        tag, text = b["tag"], b["text"]
        target = current["blocks"] if current else lead
        if tag in ("h1", "h2"):
            current = {"heading": text, "blocks": []}
            sections.append(current)
        elif tag in ("h3", "h4", "h5", "h6"):
            target.append({"kind": "heading", "text": text})
        elif tag == "li":
            if target and target[-1]["kind"] == "list":
                target[-1]["items"].append(text)
            else:
                target.append({"kind": "list", "items": [text]})
        else:
            target.append({"kind": "para", "text": text})
    return lead, sections


def main():
    os.makedirs(DEST, exist_ok=True)
    written = 0
    for name in sorted(os.listdir(EXTRACTED)):
        data = json.load(open(os.path.join(EXTRACTED, name)))
        route = data["route"].strip("/")
        if route in BESPOKE:
            continue
        title, description = meta(route)
        lead, sections = shape(data["blocks"])
        slug = name[:-5]
        body = f"""// Generated by tools/build_content.py from the mirror, then hand-edited.
// Live source: https://wforce.org{data["route"]}

import type {{ PageContent }} from "@/lib/content";

const page: PageContent = {{
  route: {ts(data["route"])},
  title: {ts(title)},
  eyebrow: {ts(EYEBROW.get(route, "WOS"))},
  description: {ts(description)},
  lead: {ts(lead)},
  sections: {ts(sections)},
}};

export default page;
"""
        open(os.path.join(DEST, f"{slug}.ts"), "w", encoding="utf-8").write(body)
        written += 1
    print(f"{written} content files written, {len(BESPOKE)} left bespoke")


if __name__ == "__main__":
    main()
