#!/usr/bin/env python3
"""
Pull the nine blog cards out of the mirror's /blog/ index into content/posts.ts.

Cards for the archive, plus each post's own body from its page. Excerpts are the live site's own
truncated ones, ellipsis included. The dated URLs in the card meta (/2025/05/15/) are
date archives; the post itself lives at a slug.

Usage: python3 tools/extract_posts.py
"""

import html
import json
import os
import re
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))
MIRROR = os.path.join(HERE, "..", "..", "wforce-mirror", "wforce.org")

# One card: the linked title, then the date, then the excerpt, in markup order.
CARD = re.compile(
    r'<a[^>]*href="\.\./([a-z0-9-]+)/"[^>]*>\s*<h4[^>]*>(.*?)</h4>\s*</a>'
    r'(.*?)(?=<a[^>]*post-title__link|</body>)',
    re.S,
)
DATE = re.compile(r'href="\.\./(\d{4})/(\d{2})/(\d{2})/"')
TAGS = re.compile(r"<[^>]+>")
STRIP = re.compile(r"<(script|style|noscript|svg|form)\b.*?</\1>", re.S | re.I)
BLOCK = re.compile(r"<(h2|h3|h4|h5|h6|p|li)\b[^>]*>(.*?)</\1>", re.S | re.I)


def body_of(slug):
    """Every block on the post page. The chrome is filtered out by frequency later."""
    src = STRIP.sub(" ", html.unescape(
        open(os.path.join(MIRROR, slug, "index.html"), encoding="utf-8",
             errors="replace").read()))
    return [(t.lower(), text(inner)) for t, inner in BLOCK.findall(src) if text(inner)]


def text(raw):
    return re.sub(r"\s+", " ", html.unescape(TAGS.sub(" ", raw))).strip()


def main():
    src = html.unescape(
        open(os.path.join(MIRROR, "blog", "index.html"), encoding="utf-8",
             errors="replace").read()
    )

    posts, seen = [], set()
    for slug, title, rest in CARD.findall(src):
        if slug in seen:
            continue
        seen.add(slug)
        date = DATE.search(rest)
        excerpt = re.search(r"<p\b[^>]*>(.*?)</p>", rest, re.S)
        # The featured image sits above the title in the card, so it is the last one
        # before this anchor, not the first one after it.
        before = src[: src.index(f'href="../{slug}/"')]
        image = None
        for image in re.finditer(r'<img[^>]+src="([^"]*wp-content/uploads/[^"]+)"', before):
            pass
        posts.append({
            "slug": slug,
            "date": "-".join(date.groups()) if date else "",
            "title": text(title),
            "excerpt": text(excerpt.group(1)) if excerpt else "",
            "image": "/images/" + os.path.basename(image.group(1)) if image else None,
        })

    # A block on more than half the posts is the nav, the footer, or the comment form.
    raw = {p["slug"]: body_of(p["slug"]) for p in posts}
    counts = Counter(b for blocks in raw.values() for b in set(blocks))
    chrome = {b for b, n in counts.items() if n > len(raw) / 2}
    for post in posts:
        post["blocks"] = [
            {"kind": "heading" if t != "p" else "para", "text": v}
            for t, v in raw[post["slug"]] if (t, v) not in chrome
        ]

    body = """// The blog archive, from /blog/ on the live site.
//
// Generated by tools/extract_posts.py. Excerpts are the live site's own truncated ones.
// Post bodies are extracted separately, from each post's own page in the mirror.

export type Post = {
  slug: string;
  date: string;
  title: string;
  excerpt: string;
  image: string | null;
  blocks: { kind: "heading" | "para"; text: string }[];
};

export const POSTS: Post[] = %s;
""" % json.dumps(posts, indent=2, ensure_ascii=False)
    body = re.sub(r'"(slug|date|title|excerpt|image|blocks|kind|text)":', r"\1:", body)
    open(os.path.join(HERE, "..", "content", "posts.ts"), "w", encoding="utf-8").write(body)
    for p in posts:
        print(f"{p['date']}  {p['slug'][:42]:<44} {len(p['blocks']):>2} blocks")


if __name__ == "__main__":
    main()
